export const TYPE_OF_SERVICE_PROVIDER = {
    PLAYROOM: "PLAYROOM",
    CATERING: "CATERING",
    ANIMATOR: "ANIMATOR"
  };

export const ROLE = {
    ROLE_ADMINISTRATOR: "ROLE_ADMINISTRATOR",
    ROLE_SERVICE_PROVIDER: "ROLE_SERVICE_PROVIDER",
    ROLE_USER: "ROLE_USER"
}